apiVersion: v1
kind: Service
metadata:
  name: Census-Service
  labels:
    app: Census-devops

spec:
  selector:
    app: myapp-devops
  type: LoadBalancer

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31201