apiVersion: apps/v1
kind: Deployment
metadata:
  name: Census-Deployment

spec:
  selector:
    matchLabels:
      app: Census-devops
  replicas: 2

  template:
    metadata:
      labels:
        app: Census-devops
    spec:
      containers:
        - name: Census-devops
          image: ptemghare/census-mgmt:docker_tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080