apiVersion: v1
kind: Service
metadata:
  name: census-service
  labels:
    app: census-devops

spec:
  selector:
    app: census-devops
  type: LoadBalancer

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31201